modLoader = "javafml"
loaderVersion="[47,)"
license = "MIT License"
[[mods]]
modId = "create_mechanical_extruder"
version = "${file.jarVersion}"
displayName = "Create Mechanical Extruder"
logoFile="logo.png"
description = '''
Gather blocks from fluid combinations.
'''

[[dependencies.create_mechanical_extruder]]
    modId = "forge"
    mandatory = true
    versionRange="[47.1.43,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.create_mechanical_extruder]]
    modId = "minecraft"
    mandatory = true
    versionRange="[1.20,1.21)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.create_mechanical_extruder]]
    modId = "create"
    mandatory = true
    versionRange="[0.5.1.i,)"
    ordering = "AFTER"
    side = "BOTH"
